# If you are not sure what all these fields mean, please refer our documentation here:
# http://evalai.readthedocs.io/en/latest/challenge_creation.html#challenge-creation-using-zip-configuration
title: PyMalta - First steps towards ML - Part 2 - Challenge
short_description: PyMalta - First steps towards ML - Part 2 - Challenge
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description:
evaluation_script: evaluation_script.zip
remote_evaluation: False
start_date: 2019-01-01 00:00:00
end_date: 2099-05-31 23:59:59
published: True

leaderboard:
  - id: 1
    schema: { "labels": ["Accuracy", "Precision", "Recall", "F1-Score"], "default_order_by": "F1-Score" }

challenge_phases:
  - id: 1
    name: Challenge
    description: templates/challenge_phase_description.html
    leaderboard_public: True
    is_public: True
    start_date: 2019-01-01 00:00:00
    end_date: 2099-05-24 23:59:59
    test_annotation_file: annotations/forest_cover_submission.csv
    codename: challenge
    max_submissions_per_day: 15
    max_submissions_per_month: 15
    max_submissions: 15

dataset_splits:
  - id: 1
    name: Challenge
    codename: challenge

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
